Removing enable_unsafe_noiommu_mode=1 as a parameter
And configuring it in a different way:
echo 1 | sudo tee /sys/module/vfio/parameters/enable_unsafe_noiommu_mode

The parameter fails in same guest images:
[root@trex cloud-user]# /root/dpdk/usertools/dpdk-devbind.py -b vfio-pci 0000:05:00.0 0000:06:00.0
Error: bind failed for 0000:05:00.0 - Cannot bind to driver vfio-pci: [Errno 22] Invalid argument
Error: bind failed for 0000:06:00.0 - Cannot bind to driver vfio-pci: [Errno 22] Invalid argument

Change-Id: I237fcaccb88c53dbe6d76d9f6a36200dc949f8e4
(cherry picked from commit 0ab18744dca321ee43ca0116f7d03bc451f575a3)