Print ovn version for setups in which ovn is being used
For ml2/ovs setups it is failing because task "Retrieve OVN Version"
is skipped and ovn_version variable is not set
Error: The conditional check 'ovn_version.stdout != ""' failed.

Change-Id: I8d681c5d1ca45d9b24754e866a58862c62270e61